SET MODE MYSQL;
DROP TABLE IF EXISTS AUTHORS;
CREATE TABLE AUTHORS(
ID BIGINT PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(255) UNIQUE
);

DROP TABLE IF EXISTS GENRES;
CREATE TABLE GENRES(
ID BIGINT PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(255) UNIQUE
);

DROP TABLE IF EXISTS BOOKS;
CREATE TABLE BOOKS(
ID BIGINT PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(255),
AUTHOR_ID BIGINT,
CONSTRAINT BOOKS_AUTHORS_FK
FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS(ID),
GENRE_ID BIGINT,
CONSTRAINT BOOKS_GENRE_FK
FOREIGN KEY (GENRE_ID) REFERENCES GENRES(ID)
);
