spring:
  shell:
    interactive:
      enabled: true
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
        trace: true
  datasource:
    url: jdbc:h2:mem:testdb
    schema: classpath:schema.sql
    #    data: classpath:data.sql
    initialization-mode: always
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
  data:
    mongodb:
      port: 8089
      database: testdb
  batch:
    job:
      enabled: false
    initialize-schema: always
mongock:
  enabled: true
  #  runner-type: "ApplicationRunner" # default
  runner-type: "InitializingBean"
  change-logs-scan-package: ru.otus.homework.mongock.changelog

