#spring:
#  datasource:
#    url: jdbc:h2:mem:testdb
#    schema: schema.sql
#    data: data.sql
#    initialization-mode: always
#  jpa:
#    generate-ddl: false
#    hibernate:
#      ddl-auto: none
#    show-sql: true
#  shell:
#    interactive:
#      enabled: true

spring:
  data:
    mongodb:
      database: company

mongock:
  runner-type: "ApplicationRunner" # default
  #runner-type: "InitializingBean"
#  change-logs-scan-package:
#    - ru.otus.spring.mongock.changelog