--SET MODE MYSQL;
DROP TABLE IF EXISTS AUTHORS;
CREATE TABLE AUTHORS(
ID BIGINT AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR(255) UNIQUE
);

DROP TABLE IF EXISTS GENRES;
CREATE TABLE GENRES(
ID BIGINT AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR(255) UNIQUE
);

DROP TABLE IF EXISTS BOOKS;
CREATE TABLE BOOKS(
ID BIGINT PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(255),
AUTHOR_ID BIGINT,
CONSTRAINT BOOKS_AUTHORS_FK
FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS(ID),
GENRE_ID BIGINT,
CONSTRAINT BOOKS_GENRE_FK
FOREIGN KEY (GENRE_ID) REFERENCES GENRES(ID)
);

DROP TABLE IF EXISTS COMMENTS;
CREATE TABLE COMMENTS(
ID BIGINT PRIMARY KEY AUTO_INCREMENT,
TEXT VARCHAR(255),
BOOK_ID BIGINT,
CONSTRAINT COMMENTS_BOOKS_FK
FOREIGN KEY (BOOK_ID) REFERENCES BOOKS(ID)
ON DELETE CASCADE
);

DROP TABLE IF EXISTS USERS;
CREATE TABLE USERS(
ID BIGINT PRIMARY KEY AUTO_INCREMENT,
USERNAME VARCHAR(255) UNIQUE,
PASSWORD VARCHAR(255)
);


DROP TABLE IF EXISTS ROLES;
CREATE TABLE USER_ROLES(
USER_ID BIGINT,
ROLES VARCHAR(255)
);