version: "3"
services:
  application:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8080
    ports:
      - 8080:8080
    environment:
      MY_SQL_USER: root
      MY_SQL_PASSWORD: root
      DB_URL: jdbc:mysql://mysqldb:3306/mysqldb
    depends_on:
      - db
  db:
    container_name: mysqldb
    image: mysql/mysql-server:8.0.24
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysqldb
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3306:3306